<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>オセロ - Othello</title>
    <link rel="stylesheet" href="assets/css/style.css">
    <link rel="stylesheet" href="assets/css/othello.css">
</head>
<body>
    <div class="container othello-container">
        <h1>オセロ</h1>
        
        <div class="rules-link-container">
            <a href="./othello-rules.php" class="rules-link">📖 ルールを見る</a>
            <a href="./" class="rules-link">🏠 トップに戻る</a>
        </div>
        
        <div class="game-info">
            <div class="player-info">
                <div class="player-display black-player">
                    <div class="player-icon">⚫</div>
                    <div class="player-details">
                        <div class="player-label">黒</div>
                        <div id="black-count" class="piece-count">2</div>
                    </div>
                </div>
                
                <div id="turn-indicator" class="turn-indicator">
                    <span id="current-player-text">⚫ 黒の番</span>
                </div>
                
                <div class="player-display white-player">
                    <div class="player-icon">⚪</div>
                    <div class="player-details">
                        <div class="player-label">白</div>
                        <div id="white-count" class="piece-count">2</div>
                    </div>
                </div>
            </div>
            
            <div id="game-status" class="game-status"></div>
            <div id="pass-message" class="pass-message"></div>
        </div>

        <div id="board" class="othello-board">
            <!-- 8x8 = 64 cells will be generated by JavaScript -->
        </div>

        <button id="reset-button" class="reset-button">リセット</button>
    </div>

    <script src="assets/js/othello.js"></script>
</body>
</html>
